---
version: 2
updates:
  # Sphinx (documentation)
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "cookiecutter"
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
  # Github Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "cookiecutter"
      - "dependencies"
      - "github_actions"
    open-pull-requests-limit: 99
  # GitHub Actions Python dependencies `constraints` file
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "cookiecutter"
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
  # Project dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "cookiecutter"
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99

  ## Cookiecutter template dependencies ##
  # Sphinx (documentation)
  - package-ecosystem: pip
    directory: "/{{cookiecutter.project_slug}}/docs"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
  # Github Actions: configuration workflows
  - package-ecosystem: github-actions
    directory: "/{{cookiecutter.project_slug}}/.github"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "github_actions"
    open-pull-requests-limit: 99
  # Github Actions: primary workflows
  - package-ecosystem: github-actions
    directory: "/{{cookiecutter.project_slug}}/.github/workflows"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "github_actions"
    open-pull-requests-limit: 99
  # GitHub Actions Python dependencies `constraints` file
  - package-ecosystem: pip
    directory: "/{{cookiecutter.project_slug}}/.github/workflows"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
  # Project dependencies
  - package-ecosystem: pip
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
  # Dockerfile
  - package-ecosystem: docker
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
