---
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: tests/.*$

  # For IDE-integration outside of the pre-commit hook,
  # see: https://black.readthedocs.io/en/stable/editor_integration.html
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
        exclude: ^{{cookiecutter\.project_slug}}/tests/test_main\.py$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        exclude: poetry.lock

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.0.0
    hooks:
      - id: flakeheaven
        # False-positives from cookiecutter Jinja2 template syntax =>
        # print output but always succeed.
        # see: https://stackoverflow.com/a/59745587
        verbose: true
        entry: bash -c 'flakeheaven lint "$@" || true' --

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        args: [--maxdepth=3, -i]
        exclude: ^(docs/source/.*)|({{cookiecutter\.project_slug}}/(README\.md|docs/source/.*))$

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        # False-positives from cookiecutter Jinja2 template syntax =>
        # print output but always succeed.
        # see: https://stackoverflow.com/a/59745587
        verbose: true
        entry: bash -c '.tox/precommit/bin/mypy "$@" || true' --
        args: [--cache-dir=/dev/null, --config-file=pyproject.toml]
        types: [python]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        # False-positives from cookiecutter Jinja2 template syntax =>
        # print output but always succeed.
        # see: https://stackoverflow.com/a/59745587
        verbose: true
        entry: bash -c '.tox/precommit/bin/pylint "$@" || true' --
        args: [--rcfile=pyproject.toml]
        types: [python]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: script-must-have-extension
      - id: script-must-not-have-extension

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        minimum_pre_commit_version: 2.17.0
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.1.2]
        entry: shfmt
        args: [-w]
        types: [shell]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: ['-d {extends: default, rules: {line-length: {max: 120, level: warning}}}']
        exclude: ^{{cookiecutter\.project_slug}}/\.github/workflows/(auto-merge-dependabot|ci|release|publish_benchmarks|publish_log4brains)\.yml$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files  # Ignored for git-lfs files
        args: [--maxkb=100000]  # 100MB
      - id: debug-statements
        exclude: ^{{cookiecutter.project_slug}}/tests/test_main\.py
      - id: end-of-file-fixer  # Ensure files ONLY end in a newline
        exclude_types: [jupyter]
      - id: trailing-whitespace  # Trim
        args: [--markdown-linebreak-ext=md]
