---
name: Auto-Merge-Dependabot

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows:
      # Upstream workflow runs on PRs to main/master and always completes;
      # needed because Dependabot-initiated pushes to master do not have access
      # to repository secrets on which this workflow relies.
      # see: dependabot/dependabot-core/issues/3253
      - Dependabot PR Check
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: {{ "${{ secrets.AUTO_MERGE_DEPENDABOT_TOKEN }}" }}
