---
name: Publish ADR Documentation via Log4brains
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
env:
  BUILD_DIR: .log4brains/out

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          # yamllint disable-line rule:line-length
          persist-credentials: false  # required by JamesIves/github-pages-deploy-action
          # yamllint disable-line rule:line-length
          fetch-depth: 0  # required by Log4brains to work correctly (needs the whole Git history)
      - name: Install Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - name: Install and Build Log4brains
        run: |
          npm install -g log4brains
          log4brains build \
            --basePath "/${GITHUB_REPOSITORY#*/}/adl" \
            --out "${BUILD_DIR}/adl"
          touch "${BUILD_DIR}/.nojekyll"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ env.BUILD_DIR }}
