---
name: Reset Instance

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main  # forward-compatibility with new GitHub default branch naming
      - master  # backward-compatibility with old GitHub default branch naming
  workflow_run:
    workflows:
      - Dependabot PR Check
    types:
      - completed

env:
  COOKIECUTTER_META_PROJECT: cookiecutter-cruft-poetry-tox-pre-commit-ci-cd
  META_PROJECT_REPO: TeoZosa/cookiecutter-cruft-poetry-tox-pre-commit-ci-cd
  # yamllint disable-line rule:line-length
  COOKIECUTTER_PROJECT_INSTANCE: cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance
  # yamllint disable-line rule:line-length
  PROJECT_INSTANCE_REPO: TeoZosa/cookiecutter-cruft-poetry-tox-pre-commit-ci-cd-instance
  PIP_CONSTRAINTS_FILE: .github/workflows/constraints.txt

jobs:
  instance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ env.COOKIECUTTER_META_PROJECT }}
        uses: actions/checkout@v2.3.4
        with:
          path: ${{ env.COOKIECUTTER_META_PROJECT }}

      - name: Check out ${{ env.COOKIECUTTER_PROJECT_INSTANCE }}
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{ env.PROJECT_INSTANCE_REPO }}
          path: ${{ env.COOKIECUTTER_PROJECT_INSTANCE }}
          token: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.9"

      - name: Install cruft
        working-directory: ${{ env.COOKIECUTTER_META_PROJECT }}
        run: |
          pip install --constraint="${PIP_CONSTRAINTS_FILE}" pip
          pip install --constraint="${PIP_CONSTRAINTS_FILE}" cruft

      - name: Remove working tree
        run: |
          mv "${COOKIECUTTER_PROJECT_INSTANCE}/.git" tmp.git
          rm -rf "${COOKIECUTTER_PROJECT_INSTANCE}"
          mkdir "${COOKIECUTTER_PROJECT_INSTANCE}"
          mv tmp.git "${COOKIECUTTER_PROJECT_INSTANCE}/.git"

      - name: Invoke cruft
        run: |
          cruft \
            create \
            https://github.com/"${META_PROJECT_REPO}" \
            --overwrite-if-exists \
            --no-input \
            --checkout="${GITHUB_REF##*/}" \
            --extra-context="${extra_context}"
        env:
          extra_context: |
            {
              "project_name": "${{ env.COOKIECUTTER_PROJECT_INSTANCE }}",
              "project_type": "package",
              "jupyter_notebook_support": "yes"
            }

      # yamllint disable-line rule:line-length
      - name: Run README ToC generator and auto-formatting pre-commit hooks on ${{ env.COOKIECUTTER_PROJECT_INSTANCE }}
        working-directory: ${{ env.COOKIECUTTER_PROJECT_INSTANCE }}
        run: |
          pip install --constraint="${PIP_CONSTRAINTS_FILE}" pre-commit
          for hook in markdown-toc black trailing-whitespace end-of-file-fixer
          do
            pre-commit run "${hook}" -vv --all-files --color always || true
          done

      - name: Install Poetry
        working-directory: ${{ env.COOKIECUTTER_PROJECT_INSTANCE }}
        run: |
          pip install --constraint="${PIP_CONSTRAINTS_FILE}" poetry
          poetry --version

      - name: Add poetry lockfile for ${{ env.COOKIECUTTER_PROJECT_INSTANCE }}
        working-directory: ${{ env.COOKIECUTTER_PROJECT_INSTANCE }}
        run: |
          poetry update --lock

      - name: Create commit
        run: |
          cd "${COOKIECUTTER_META_PROJECT}"
          author="$(git show --no-patch --format='%an <%ae>')"
          date="$(git show --no-patch --format=%ad)"
          message="$(git show --no-patch --format=%B | sed 's/ *(#[0-9]\+)//g')

          Original-Commit: ${META_PROJECT_REPO}@${GITHUB_SHA::7}"

          cd "../${COOKIECUTTER_PROJECT_INSTANCE}"
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit \
            --allow-empty \
            --author="$author" \
            --date="$date" \
            --message="$message"

      - name: Push to instance
        run: |
          git \
            -C "${COOKIECUTTER_PROJECT_INSTANCE}" \
            push \
            "${COOKIECUTTER_PROJECT_INSTANCE_GIT_URL}" \
            HEAD:"${GITHUB_REF##*/}"
        env:
          # yamllint disable-line rule:line-length
          COOKIECUTTER_PROJECT_INSTANCE_GIT_URL: "https://${{ env.GITHUB_ACTOR }}:${{ env.GITHUB_TOKEN }}@github.com/${{ env.PROJECT_INSTANCE_REPO }}.git"
